### ISSUE TITLE
Not all animations supported

### ISSUE THREAD

**Issue by adawolfs** [2d-inc/Flare-JS#18]
Testing https://github.com/2d-inc/Flare-Flutter/tree/master/example/simple/assets I found that most of them are not supported, rendering only a white shadow or nothing at all with following error on console.
```
example.js:181 Uncaught TypeError: Cannot read property 'initialize' of null
    at FlareExample.setActor (example.js:181)
    at example.js:155
    at _LoadNestedAssets (ActorLoader.js:653)
    at _ReadActor (ActorLoader.js:735)
    at FileReader.fileReader.onload (ActorLoader.js:1438)
```

**Comment by umberto-sonnino** [comment]
Thanks for the report! I've removed the files that weren't working properly in Flutter.

I'll close the issue as this is the tracker for our Javascript runtime!
