### ISSUE TITLE
Examples are not working q.cb is not a function

### ISSUE THREAD

**Issue by crtl** [2d-inc/Flare-JS#35]
Hello,
I cant try out the example.
Ive downloaded the files and copied gl-matrix.js into the build dir but it still does not work.

Console:

```
Uncaught TypeError: q.cb is not a function
    at Graphics.js:73
(anonymous)	@	Graphics.js:73
setTimeout (async)		
(anonymous)	@	Graphics.js:67
Promise.then (async)		
initialize	@	Graphics.js:59
FlareExample	@	example.js:20
onLoad	@	example.html:25
onload
```

**Comment by umberto-sonnino** [comment]
We were just working on this the other day, I've merged the PR we had in place for this.
If you pull the latest `master` it should be working now..!
