### ISSUE TITLE
Link in Flare-JS repo do not work

### ISSUE THREAD

**Issue by Joel-Nickson** [2d-inc/Flare-JS#50]
![image](https://user-images.githubusercontent.com/61058781/166318102-6d92557b-057b-4e7a-8428-e65854b422d8.png)

Please update the above mentioned link

**Comment by umberto-sonnino** [comment]
Thanks for pointing it out! 
Everything has been moving to the new version of [Rive](https://rive.app), including [our runtimes](https://help.rive.app/runtimes/overview), so upgrading is highly encouraged (if possible)!
